### ISSUE TITLE
Implement callback path

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/plugin-topdesk-integration#2]
In topdesk you can create "Actions" that can be executed when you press the `...` next to the "Operator" field.

![screen shot 2018-04-25 at 14 07 59](https://user-images.githubusercontent.com/17762105/39267587-8bad61c4-48cd-11e8-9970-0ad67910add1.png)

To define the action, follow the following steps:

<img width="1552" alt="screen shot 2018-04-26 at 09 43 52" src="https://user-images.githubusercontent.com/17762105/39292399-5bf4edc6-4936-11e8-8b84-e15e777bda26.png">

![screen shot 2018-04-25 at 14 08 37](https://user-images.githubusercontent.com/17762105/39267708-e918e9be-48cd-11e8-9efd-f403c41e7124.png)

![screen shot 2018-04-25 at 14 08 44](https://user-images.githubusercontent.com/17762105/39292324-208bbf76-4936-11e8-9703-cd59a4f53962.png)

![screen shot 2018-04-25 at 14 08 13](https://user-images.githubusercontent.com/17762105/39267692-dbdb1bb4-48cd-11e8-9fa3-a5141b1184ed.png)

Edit the action "Bericht versturen naar Stadsapp"

The events that need to be linked are:
- 2 Status wordt gewijzigd naar Wacht op aanmelder
- 4 Afmelden bestaande melding￼
- 4 Afmelden nieuwe melding

Change the HTTP method in Step 1 to `POST`
Construct the json payload. Add variables by clicking the `[]` button.

Open "Execution Logs" to see the requests which were sent to the configured URL.

**Comment by RubenMattan** [comment]
Can you create and action to `BASE_URL/plugins/topdesk_integration/callback_api`

**Comment by RubenMattan** [comment]
When testing the callback i got the following error.

POST requests require a <code>Content-length</code> header.
